name: Run app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17.0.3_7-jre-nanoserver
    steps:
      - uses: actions/download-artifact@master
        with:
          name: java-sample1
          path: .
      - name: run
      - run: java -jar java-sample1.jar